figure(1), hold on
plot(nodeArch.nodesLoc(1:nodeArch.numNode,1), nodeArch.nodesLoc(1:nodeArch.numNode,2),...
    'o','MarkerSize',5,'MarkerFaceColor','r');
plot(netArch.Sink.x, netArch.Sink.y,'o', ...
    'MarkerSize',10, 'MarkerFaceColor', 'g');